AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  SAM Template for the OSRS Cache Downloader

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    Environment:
      Variables:
        CACHE_BUCKET_NAME: "cache.api.2007scape.tools"

Resources:
  CacheDownloaderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: CacheDownloader
      Handler: cachedownloader.App::handleRequest
      Runtime: java11
      MemorySize: 512
      Role: arn:aws:iam::226176173674:role/CacheParser
      Events:
        WeeklySchedule:
          Type: Schedule # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
              Schedule: 'cron(0 12 ? * THU *)'
              Name: WeeklySchedule
              Description: run weekly aftere OSRS update
              Enabled: True

Outputs:
  HelloWorldFunction:
    Description: "Cache Downloader Lambda Function ARN"
    Value: !GetAtt CacheDownloaderFunction.Arn
